from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_COOLCompiler(object):
    def setupUi(self, COOLCompiler):
        COOLCompiler.setObjectName("COOLCompiler")
        COOLCompiler.setWindowModality(QtCore.Qt.WindowModal)
        COOLCompiler.resize(1350, 900)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/icons/Qt.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        COOLCompiler.setWindowIcon(icon)
        COOLCompiler.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(COOLCompiler)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabCOOLMenu = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabCOOLMenu.setFont(font)
        self.tabCOOLMenu.setObjectName("tabCOOLMenu")
        self.tabCode = QtWidgets.QWidget()
        self.tabCode.setObjectName("tabCode")
        self.gridLayout = QtWidgets.QGridLayout(self.tabCode)
        self.gridLayout.setObjectName("gridLayout")
        self.textCode = QtWidgets.QPlainTextEdit(self.tabCode)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textCode.setFont(font)
        self.textCode.setObjectName("textCode")
        self.gridLayout.addWidget(self.textCode, 0, 0, 1, 1)
        self.tabCOOLMenu.addTab(self.tabCode, "")
        self.tabLexer = QtWidgets.QWidget()
        self.tabLexer.setObjectName("tabLexer")
        self.textLexer = QtWidgets.QPlainTextEdit(self.tabLexer)
        self.textLexer.setGeometry(QtCore.QRect(10, 10, 1261, 591))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textLexer.setFont(font)
        self.textLexer.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textLexer.setReadOnly(True)
        self.textLexer.setObjectName("textLexer")
        self.tabCOOLMenu.addTab(self.tabLexer, "")
        self.tabParser = QtWidgets.QWidget()
        self.tabParser.setObjectName("tabParser")
        self.textParser = QtWidgets.QPlainTextEdit(self.tabParser)
        self.textParser.setGeometry(QtCore.QRect(10, 10, 1261, 591))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textParser.setFont(font)
        self.textParser.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textParser.setReadOnly(True)
        self.textParser.setObjectName("textParser")
        self.tabCOOLMenu.addTab(self.tabParser, "")
        self.tabContext = QtWidgets.QWidget()
        self.tabContext.setObjectName("tabContext")
        self.textContext = QtWidgets.QPlainTextEdit(self.tabContext)
        self.textContext.setGeometry(QtCore.QRect(10, 10, 1261, 591))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textContext.setFont(font)
        self.textContext.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textContext.setReadOnly(True)
        self.textContext.setObjectName("textContext")
        self.tabCOOLMenu.addTab(self.tabContext, "")
        self.tabScope = QtWidgets.QWidget()
        self.tabScope.setObjectName("tabScope")
        self.textScope = QtWidgets.QPlainTextEdit(self.tabScope)
        self.textScope.setGeometry(QtCore.QRect(10, 10, 1261, 591))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textScope.setFont(font)
        self.textScope.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textScope.setReadOnly(True)
        self.textScope.setObjectName("textScope")
        self.tabCOOLMenu.addTab(self.tabScope, "")
        self.tabCIL = QtWidgets.QWidget()
        self.tabCIL.setObjectName("tabCIL")
        self.textCIL = QtWidgets.QPlainTextEdit(self.tabCIL)
        self.textCIL.setEnabled(True)
        self.textCIL.setGeometry(QtCore.QRect(10, 10, 1261, 591))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textCIL.setFont(font)
        self.textCIL.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textCIL.setReadOnly(True)
        self.textCIL.setObjectName("textCIL")
        self.tabCOOLMenu.addTab(self.tabCIL, "")
        self.tabMIPS = QtWidgets.QWidget()
        self.tabMIPS.setObjectName("tabMIPS")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabMIPS)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textMIPS = QtWidgets.QPlainTextEdit(self.tabMIPS)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textMIPS.setFont(font)
        self.textMIPS.setUndoRedoEnabled(False)
        self.textMIPS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textMIPS.setReadOnly(True)
        self.textMIPS.setObjectName("textMIPS")
        self.gridLayout_2.addWidget(self.textMIPS, 0, 0, 1, 1)
        self.tabCOOLMenu.addTab(self.tabMIPS, "")
        self.tabErrors = QtWidgets.QWidget()
        self.tabErrors.setMaximumSize(QtCore.QSize(1328, 803))
        self.tabErrors.setObjectName("tabErrors")
        self.textErrors = QtWidgets.QPlainTextEdit(self.tabErrors)
        self.textErrors.setGeometry(QtCore.QRect(10, 10, 1261, 591))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textErrors.setFont(font)
        self.textErrors.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textErrors.setReadOnly(True)
        self.textErrors.setObjectName("textErrors")
        self.tabCOOLMenu.addTab(self.tabErrors, "")
        self.gridLayout_3.addWidget(self.tabCOOLMenu, 0, 0, 1, 1)
        COOLCompiler.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(COOLCompiler)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/icons/arrow-000.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuSave.setIcon(icon1)
        self.menuSave.setObjectName("menuSave")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        COOLCompiler.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(COOLCompiler)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        COOLCompiler.setStatusBar(self.statusbar)
        self.actionNewCode = QtWidgets.QAction(COOLCompiler)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/icons/selection-input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewCode.setIcon(icon2)
        self.actionNewCode.setObjectName("actionNewCode")
        self.actionGuardarResultados = QtWidgets.QAction(COOLCompiler)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/disk--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardarResultados.setIcon(icon3)
        self.actionGuardarResultados.setObjectName("actionGuardarResultados")
        self.actionLoadCode = QtWidgets.QAction(COOLCompiler)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../img/icons/blue-folder-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadCode.setIcon(icon4)
        self.actionLoadCode.setObjectName("actionLoadCode")
        self.actionExit = QtWidgets.QAction(COOLCompiler)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../img/icons/cross-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(COOLCompiler)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../img/icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon7)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAcercaInferenciaTipos = QtWidgets.QAction(COOLCompiler)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../images/lifebuoy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcercaInferenciaTipos.setIcon(icon8)
        self.actionAcercaInferenciaTipos.setObjectName("actionAcercaInferenciaTipos")
        self.actionSaveGrammarAs = QtWidgets.QAction(COOLCompiler)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../images/disk--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveGrammarAs.setIcon(icon9)
        self.actionSaveGrammarAs.setObjectName("actionSaveGrammarAs")
        self.actionAnalyse = QtWidgets.QAction(COOLCompiler)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalyse.setIcon(icon10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.actionAnalyse.setFont(font)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.actionQuickAnalyse = QtWidgets.QAction(COOLCompiler)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/controlx2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuickAnalyse.setIcon(icon11)
        self.actionQuickAnalyse.setObjectName("actionQuickAnalyse")
        self.actionRun = QtWidgets.QAction(COOLCompiler)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../img/icons/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon12)
        self.actionRun.setObjectName("actionRun")
        self.actionQuickAnalyse_2 = QtWidgets.QAction(COOLCompiler)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../images/controlx2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuickAnalyse_2.setIcon(icon13)
        self.actionQuickAnalyse_2.setObjectName("actionQuickAnalyse_2")
        self.actionAboutAuthors = QtWidgets.QAction(COOLCompiler)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../img/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAboutAuthors.setIcon(icon14)
        self.actionAboutAuthors.setObjectName("actionAboutAuthors")
        self.actionOrientation = QtWidgets.QAction(COOLCompiler)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../img/icons/lifebuoy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOrientation.setIcon(icon15)
        self.actionOrientation.setObjectName("actionOrientation")
        self.actionReport = QtWidgets.QAction(COOLCompiler)
        self.actionReport.setIcon(icon15)
        self.actionReport.setObjectName("actionReport")
        self.actionasdasd = QtWidgets.QAction(COOLCompiler)
        self.actionasdasd.setObjectName("actionasdasd")
        self.actionCode = QtWidgets.QAction(COOLCompiler)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../img/icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCode.setIcon(icon16)
        self.actionCode.setObjectName("actionCode")
        self.actionLexer = QtWidgets.QAction(COOLCompiler)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../img/icons/disk--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLexer.setIcon(icon17)
        self.actionLexer.setObjectName("actionLexer")
        self.actionParser = QtWidgets.QAction(COOLCompiler)
        self.actionParser.setIcon(icon16)
        self.actionParser.setObjectName("actionParser")
        self.actionContext = QtWidgets.QAction(COOLCompiler)
        self.actionContext.setIcon(icon17)
        self.actionContext.setObjectName("actionContext")
        self.actionScope = QtWidgets.QAction(COOLCompiler)
        self.actionScope.setIcon(icon16)
        self.actionScope.setObjectName("actionScope")
        self.actionCIL = QtWidgets.QAction(COOLCompiler)
        self.actionCIL.setIcon(icon17)
        self.actionCIL.setObjectName("actionCIL")
        self.actionMIPS = QtWidgets.QAction(COOLCompiler)
        self.actionMIPS.setIcon(icon16)
        self.actionMIPS.setObjectName("actionMIPS")
        self.actionErrors = QtWidgets.QAction(COOLCompiler)
        self.actionErrors.setIcon(icon17)
        self.actionErrors.setObjectName("actionErrors")
        self.menuSave.addAction(self.actionCode)
        self.menuSave.addAction(self.actionLexer)
        self.menuSave.addAction(self.actionParser)
        self.menuSave.addAction(self.actionContext)
        self.menuSave.addAction(self.actionScope)
        self.menuSave.addAction(self.actionCIL)
        self.menuSave.addAction(self.actionMIPS)
        self.menuSave.addAction(self.actionErrors)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNewCode)
        self.menuFile.addAction(self.actionLoadCode)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuRun.addAction(self.actionRun)
        self.menuOptions.addAction(self.actionHelp)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionOrientation)
        self.menuOptions.addAction(self.actionReport)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAboutAuthors)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(COOLCompiler)
        self.tabCOOLMenu.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(COOLCompiler)

    def retranslateUi(self, COOLCompiler):
        _translate = QtCore.QCoreApplication.translate
        COOLCompiler.setWindowTitle(_translate("COOLCompiler", "COOL Compiler"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabCode), _translate("COOLCompiler", "Code"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabLexer), _translate("COOLCompiler", "Lexer"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabParser), _translate("COOLCompiler", "Parser"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabContext), _translate("COOLCompiler", "Context"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabScope), _translate("COOLCompiler", "Scope"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabCIL), _translate("COOLCompiler", "CIL"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabMIPS), _translate("COOLCompiler", "MIPS"))
        self.tabCOOLMenu.setTabText(self.tabCOOLMenu.indexOf(self.tabErrors), _translate("COOLCompiler", "Errors"))
        self.menuFile.setTitle(_translate("COOLCompiler", "Fi&le"))
        self.menuSave.setTitle(_translate("COOLCompiler", "&Save ..."))
        self.menuRun.setTitle(_translate("COOLCompiler", "A&nalyser"))
        self.menuOptions.setTitle(_translate("COOLCompiler", "O&ptions"))
        self.actionNewCode.setText(_translate("COOLCompiler", "&New code"))
        self.actionNewCode.setStatusTip(_translate("COOLCompiler", "New code"))
        self.actionNewCode.setShortcut(_translate("COOLCompiler", "Ctrl+N"))
        self.actionGuardarResultados.setText(_translate("COOLCompiler", "Guardar resultados"))
        self.actionGuardarResultados.setStatusTip(_translate("COOLCompiler", "Guardar resultados"))
        self.actionGuardarResultados.setShortcut(_translate("COOLCompiler", "Ctrl+R"))
        self.actionLoadCode.setText(_translate("COOLCompiler", "&Load code"))
        self.actionLoadCode.setStatusTip(_translate("COOLCompiler", "Load code"))
        self.actionLoadCode.setShortcut(_translate("COOLCompiler", "Ctrl+O"))
        self.actionExit.setText(_translate("COOLCompiler", "&Exit"))
        self.actionExit.setStatusTip(_translate("COOLCompiler", "Exit"))
        self.actionExit.setShortcut(_translate("COOLCompiler", "Ctrl+F4"))
        self.actionHelp.setText(_translate("COOLCompiler", "&Help"))
        self.actionHelp.setStatusTip(_translate("COOLCompiler", "Help"))
        self.actionHelp.setShortcut(_translate("COOLCompiler", "F1"))
        self.actionAcercaInferenciaTipos.setText(_translate("COOLCompiler", "Acerca de Inferencia de Tipos"))
        self.actionAcercaInferenciaTipos.setStatusTip(_translate("COOLCompiler", "Acerca de Inferencia de Tipos"))
        self.actionSaveGrammarAs.setText(_translate("COOLCompiler", "Guardar gramática como ..."))
        self.actionSaveGrammarAs.setStatusTip(_translate("COOLCompiler", "Guardar Gramática Como"))
        self.actionAnalyse.setText(_translate("COOLCompiler", "Analizar"))
        self.actionAnalyse.setToolTip(_translate("COOLCompiler", "Analizar"))
        self.actionAnalyse.setStatusTip(_translate("COOLCompiler", "Analizar"))
        self.actionAnalyse.setShortcut(_translate("COOLCompiler", "F5"))
        self.actionQuickAnalyse.setText(_translate("COOLCompiler", "Análisis rápido"))
        self.actionQuickAnalyse.setToolTip(_translate("COOLCompiler", "Análisis rápido"))
        self.actionQuickAnalyse.setStatusTip(_translate("COOLCompiler", "Análisis rápido"))
        self.actionQuickAnalyse.setShortcut(_translate("COOLCompiler", "F9"))
        self.actionRun.setText(_translate("COOLCompiler", "&Run"))
        self.actionRun.setStatusTip(_translate("COOLCompiler", "Run"))
        self.actionRun.setShortcut(_translate("COOLCompiler", "F5"))
        self.actionQuickAnalyse_2.setText(_translate("COOLCompiler", "Análisis rápido de la gramática"))
        self.actionQuickAnalyse_2.setShortcut(_translate("COOLCompiler", "F9"))
        self.actionAboutAuthors.setText(_translate("COOLCompiler", "&About authors"))
        self.actionAboutAuthors.setStatusTip(_translate("COOLCompiler", "About authors"))
        self.actionAboutAuthors.setShortcut(_translate("COOLCompiler", "F6"))
        self.actionOrientation.setText(_translate("COOLCompiler", "&Orientation"))
        self.actionOrientation.setStatusTip(_translate("COOLCompiler", "Orientation"))
        self.actionReport.setText(_translate("COOLCompiler", "&Report"))
        self.actionReport.setStatusTip(_translate("COOLCompiler", "Report"))
        self.actionasdasd.setText(_translate("COOLCompiler", "asdasd"))
        self.actionCode.setText(_translate("COOLCompiler", "&Code"))
        self.actionCode.setShortcut(_translate("COOLCompiler", "Ctrl+1"))
        self.actionLexer.setText(_translate("COOLCompiler", "&Lexer"))
        self.actionLexer.setShortcut(_translate("COOLCompiler", "Ctrl+2"))
        self.actionParser.setText(_translate("COOLCompiler", "&Parser"))
        self.actionParser.setShortcut(_translate("COOLCompiler", "Ctrl+3"))
        self.actionContext.setText(_translate("COOLCompiler", "C&ontext"))
        self.actionContext.setShortcut(_translate("COOLCompiler", "Ctrl+4"))
        self.actionScope.setText(_translate("COOLCompiler", "&Scope"))
        self.actionScope.setShortcut(_translate("COOLCompiler", "Ctrl+5"))
        self.actionCIL.setText(_translate("COOLCompiler", "C&IL"))
        self.actionCIL.setShortcut(_translate("COOLCompiler", "Ctrl+6"))
        self.actionMIPS.setText(_translate("COOLCompiler", "&MIPS"))
        self.actionMIPS.setShortcut(_translate("COOLCompiler", "Ctrl+7"))
        self.actionErrors.setText(_translate("COOLCompiler", "&Errors"))
        self.actionErrors.setShortcut(_translate("COOLCompiler", "Ctrl+8"))
