WRONG_SIGNATURE = 'Method "%s" already defined in "%s" with a different signature.'
SELF_IS_READONLY = 'Variable "self" is read-only.'
LOCAL_ALREADY_DEFINED = 'Variable "%s" is already defined in method "%s".'
INCOMPATIBLE_TYPES = 'Cannot convert "%s" into "%s".'
VARIABLE_NOT_DEFINED = 'Variable "%s" is not defined in "%s".'
INVALID_OPERATION = 'Operation is not defined between "%s" and "%s".'
INVALID_TYPE = "SELF_TYPE is not valid"
AUTOTYPE_ERROR = "Incorrect use of AUTO_TYPE"
METHOD_NOT_DEFINED = 'Dispatch to undefined method "%s".'
CASE_BRANCH_ERROR = 'Duplicate branch "%s" in case statement.'
SELF_ERROR = 'Cannot use "self" as identifier'
ALREADY_DEFINED = '"%s" is already defined'
MAIN_CLASS_ERROR = "Class Main must contain a method main"
MAIN_PROGRAM_ERROR = "Program must contain a class Main"
