_LexicographicError = '(%d,%d) - LexicographicError: ERROR "%s"'
_SyntacticError = '(%d, %d) - SyntacticError: ERROR at or near "%s"'
_TypeError = '(%d, %d) - TypeError: %s'
_NameError = '(%d, %d) - NameError: %s'
_SemanticError = '(%d, %d) - SemanticError: %s'
_AtributeError = '(%d, %d) - AttributeError: %s'