TYPERROR1 = "TypeError: Illegal comparison with a basic type."
TYPERROR2 = "TypeError: non-Int arguments:"
TYPERROR3 = "TypeError: Argument of '%s' has type %s instead of %s."
TYPERROR4 = "TypeError: Loop condition does not have type Bool."
TYPERROR5 = "TypeError: Loop body does not have type Object."
TYPERROR6 = "TypeError: Predicate of 'if' does not have type Bool."
TYPERROR7 = "TypeError: Expression type %s does not conform to declared static dispatch type %s."
TYPERROR8 = "TypeError: In call of method %s, type %s of parameter %s does not conform to declared type %s."
TYPERROR9 = "TypeError: Inferred type %s of assignment expression for variable %s does not conform to declared type %s."
TYPERROR10 = "TypeError: 'new' used with undefined class %s."
TYPERROR11 = "TypeError: Undeclared type %s."
TYPERROR12 = "TypeError: Inferred type %s of initialization of attribute %s does not conform to declared type %s."
TYPERROR13 = "TypeError: Inferred return type %s of method %s does not conform to declared return type %s."
TYPERROR14 = "TypeError: Class %s inherits from an undefined class %s."
TYPERROR15 = "TypeError: Class %s of case branch is undefined."
TYPERROR16 = "TypeError: Inferred type %s of initialization of %s does not conform to identifier's declared type %s."
TYPERROR17 = "TypeError: Undefined return type Integrer in method %s."

ATTRERROR1 = "AttributeError: Dispatch to undefined method %s."

SEMERROR1 = "SemanticError: Method %s called with wrong number of arguments."
SEMERROR2 = "SemanticError: Redefinition of basic class %s."
SEMERROR3 = "SemanticError: Class %s cannot inherit class %s."
SEMERROR4 = "SemanticError: Attribute %s is multiply defined in class."
SEMERROR5 = "SemanticError: Method %s is multiply defined."
SEMERROR6 = "SemanticError: Class %s, or an ancestor of %s, is involved in an inheritance cycle."
SEMERROR7 = "SemanticError: Duplicate branch %s in case statement."
SEMERROR8 = "SemanticError: Wrong redefinition of method %s."
SEMERROR9 = "SemanticError: Attribute %s is an attribute of an inherited class."
SEMERROR10 = "SemanticError: Cannot assign to 'self'."
SEMERROR11 = "SemanticError: 'self' cannot be bound in a '%s' expression."
SEMERROR12 = "SemanticError: 'self' cannot be the name of %s."

RNTERROR1 = "RuntimeError: Expression cant\'t be Void type."
RNTERROR2 = "RuntimeError: None expression selected"

NAMERROR1 = "NameError: Undeclared identifier %s."

