name: Run

on: [push, pull_request]


jobs:
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src
          bash coolc.sh comment1.cl